export const SEARCH_BOOK_INITIAL = 'SEARCH_BOOK_INITIAL'
export const SEARCH_BOOK_START = 'SEARCH_BOOK_START'
export const SEARCH_BOOK_SUCCESS = 'SEARCH_BOOK_SUCCESS'
export const SEARCH_BOOK_FAILED = 'SEARCH_BOOK_FAILED'
